default_platform :ios

lane :beta do
  sh "npm run build"
  sh "npx cap sync ios"
  build_app(
    project: "ios/App/App.xcodeproj",
    scheme: "App",
    export_method: "app-store"
  )
  upload_to_testflight
end

lane :build_only do
  sh "npm run build"
  sh "npx cap sync ios"
  build_app(
    project: "ios/App/App.xcodeproj",
    scheme: "App",
    export_method: "app-store"
  )
end
